/** Categorias predefinidas de intereses, ofrecidas al registrarse y al editar el perfil. */
export const INTEREST_CATEGORIES: string[] = [
  'Música',
  'Cine y series',
  'Lectura',
  'Fotografía',
  'Viajes',
  'Cocina',
  'Café',
  'Arte y diseño',
  'Baile',
  'Fitness y gym',
  'Yoga',
  'Running',
  'Ciclismo',
  'Senderismo',
  'Fútbol',
  'Videojuegos',
  'Tecnología',
  'Moda',
  'Mascotas',
  'Naturaleza',
  'Playa',
  'Montaña',
  'Idiomas',
  'Emprendimiento',
  'Voluntariado',
  'Comedia',
  'Anime',
  'Teatro',
  'Vino y cerveza',
  'Fiestas',
];
